[package]
name = "const-rsa"
authors = ["Leon Farafonov <leofaraf@proton.me>"]
version = "0.0.1"
edition = "2021"

[lib]
proc_macro = true
path = "src/lib.rs"

[dependencies]
rand = "0.8.5"
rsa = "0.9.6"